config/routes.rb
Rails.application.routes.draw do
  
  
  resources :disfrazs

  devise_for :clientes , controllers: { sessions: "clientes/sessions", registrations: "clientes/registrations" }
  devise_for :vendedors , controllers: { sessions: "vendedors/sessions", registrations: "vendedors/registrations" }
  as :vendedor do
  get "/vendedors/sign_up", to: "vendedors/registrations#new", as: "register"
end

  get '/carrito' => 'cart#index'
  get '/carrito/vaciar' =>  'cart#clearCart'
  get '/carrito/solicitar' => 'cart#solicitar'
  get '/carrito/:id' => 'cart#add'
  get '/carrito/eliminar/:id' => 'cart#eliminardisfraz'
  get '/carrito/añadir/:id' => 'cart#anadirdisfraz'
  get '/carrito/quitar/:id' => 'cart#quitardisfraz'
  get '/arrendar/:id' => 'pedidos#aceptarPedido'
  get '/devolucion/:id' => 'arriendos#devolucion'

  get 'home/index'

  get 'home/ayuda'

  get 'home/acerca'

  get 'home/contacto'

  get 'vendedors/index'

  get 'vendedors/show'

  get 'clientes/:id' => 'clientes#show'

  get 'transicion_arriendos/show'

  get 'pedido_estados/show'

  get 'pedidos/index'

  get 'pedidos/show'

  get 'parametro_sistemas/index'

  get 'parametro_sistemas/show'

  get 'nota_de_ventas/index'

  get 'nota_de_ventas/show'

  get 'multas/index'

  get 'multas/show'

  get '/log_auditorias' => 'log_auditoria#index'
  get 'log_auditorias/index'

  get 'log_auditorias/show'

  get 'ejemplar_estados/index'

  get 'ejemplars/index'

  get 'ejemplars/show'

  get 'disfrazs/index'

  get 'disfrazs/show'

  get 'devolucions/index'

  get 'devolucions/show'

  get 'detalle_devolucions/show'

  get 'detalle_arriendos/show'

  get 'clientes/index'

  get 'clientes/show'

  get 'categorias/index'

  get 'categoria/new' => 'categoria#new'

  post 'categoria/index' => 'categorias#create'

  get 'categoria/index' => 'categorias#index'

  get '/arriendo_estados' => 'arriendo_estados#index'

  get 'arriendo_estado/new' => 'arriendo_estados#new'

  resources :clientes do
    resources :pedidos, :arriendos, :devolucions
    resource :cliente_estado
  end

  resources :categoria

  resources :categorias do
    resources :disfrazs
  end

  resources :cliente_estados

  resources :arriendos do
    resources :detalle_arriendos,:devolucions
    resource :transicion_est_arriendo, :multa,:nota_de_venta
  end

  resources :devolucions
  resources :disfrazs do
    resources :ejemplars
  end

  resources :ejemplars do
    resource :ejemplar_estado
  end

  resources :ejemplar_estados

  resources :log_auditorias

  resources :multas
  resources :nota_de_ventas

  resources :parametro_sistemas

  resources :pedidos do
    resources :pedidos_detalles
  end

  resources :transicion_arriendos
  resources :transicion_est_arriendos
  resources :transicion_est_ejemplars
  resources :transicion_est_pedidos
  resources :transicion_est_vendedors

  resources :vendedors do
    resources :arriendos, :devolucions
    resource :vendedor_estado
  end

  resources :log_auditorias
  resources :vendedor_estados

   root 'home#index'

end

app/models/vendedor_estado.rb
class VendedorEstado < ActiveRecord::Base
		self.table_name = "vendedor_estado"

end

app/controllers/vendedor_estados_controller.rb
class VendedorEstadosController < ApplicationController
  before_action :set_vendedor_estado, only: [:show, :edit, :update, :destroy]

  # GET /vendedor_estados
  # GET /vendedor_estados.json
  def index
    @vendedor_estados = VendedorEstado.all
  end

  # GET /vendedor_estados/1
  # GET /vendedor_estados/1.json
  def show
  end

  # GET /vendedor_estados/new
  def new
    @vendedor_estado = VendedorEstado.new
  end

  # GET /vendedor_estados/1/edit
  def edit
  end

  # POST /vendedor_estados
  # POST /vendedor_estados.json
  def create
    @vendedor_estado = VendedorEstado.new(vendedor_estado_params)

    respond_to do |format|
      if @vendedor_estado.save
        format.html { redirect_to @vendedor_estado, notice: 'Vendedor estado was successfully created.' }
        format.json { render :show, status: :created, location: @vendedor_estado }
      else
        format.html { render :new }
        format.json { render json: @vendedor_estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendedor_estados/1
  # PATCH/PUT /vendedor_estados/1.json
  def update
    respond_to do |format|
      if @vendedor_estado.update(vendedor_estado_params)
        format.html { redirect_to @vendedor_estado, notice: 'Vendedor estado was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendedor_estado }
      else
        format.html { render :edit }
        format.json { render json: @vendedor_estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendedor_estados/1
  # DELETE /vendedor_estados/1.json
  def destroy
    @vendedor_estado.destroy
    respond_to do |format|
      format.html { redirect_to vendedor_estados_url, notice: 'Vendedor estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendedor_estado
      @vendedor_estado = VendedorEstado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendedor_estado_params
      params[:vendedor_estado]
    end
end

app/helpers/vendedor_estados_helper.rb
module VendedorEstadosHelper
end

app/views/vendedor_estados/_form.html.erb
<%= form_for(@vendedor_estado) do |f| %>
  <% if @vendedor_estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendedor_estado.errors.count, "error") %> prohibited this vendedor_estado from being saved:</h2>

      <ul>
      <% @vendedor_estado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendedor_estados/edit.html.erb
<h1>Editing vendedor_estado</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendedor_estado %> |
<%= link_to 'Back', vendedor_estados_path %>

app/views/vendedor_estados/index.html.erb
<h1>Listing vendedor_estados</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendedor_estados.each do |vendedor_estado| %>
      <tr>
        <td><%= link_to 'Show', vendedor_estado %></td>
        <td><%= link_to 'Edit', edit_vendedor_estado_path(vendedor_estado) %></td>
        <td><%= link_to 'Destroy', vendedor_estado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendedor estado', new_vendedor_estado_path %>

app/views/vendedor_estados/new.html.erb
<h1>New vendedor_estado</h1>

<%= render 'form' %>

<%= link_to 'Back', vendedor_estados_path %>

app/views/vendedor_estados/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_vendedor_estado_path(@vendedor_estado) %> |
<%= link_to 'Back', vendedor_estados_path %>