config/routes.rb
Rails.application.routes.draw do
  
  
  resources :disfrazs

  devise_for :clientes , controllers: { sessions: "clientes/sessions", registrations: "clientes/registrations" }
  devise_for :vendedors , controllers: { sessions: "vendedors/sessions", registrations: "vendedors/registrations" }
  as :vendedor do
  get "/vendedors/sign_up", to: "vendedors/registrations#new", as: "register"
end

  get '/carrito' => 'cart#index'
  get '/carrito/vaciar' =>  'cart#clearCart'
  get '/carrito/solicitar' => 'cart#solicitar'
  get '/carrito/:id' => 'cart#add'
  get '/carrito/eliminar/:id' => 'cart#eliminardisfraz'
  get '/carrito/añadir/:id' => 'cart#anadirdisfraz'
  get '/carrito/quitar/:id' => 'cart#quitardisfraz'
  get '/arrendar/:id' => 'pedidos#aceptarPedido'
  get '/devolucion/:id' => 'arriendos#devolucion'

  get 'home/index'

  get 'home/ayuda'

  get 'home/acerca'

  get 'home/contacto'

  get 'vendedors/index'

  get 'vendedors/show'

  get 'clientes/:id' => 'clientes#show'

  get 'transicion_arriendos/show'

  get 'pedido_estados/show'

  get 'pedidos/index'

  get 'pedidos/show'

  get 'parametro_sistemas/index'

  get 'parametro_sistemas/show'

  get 'nota_de_ventas/index'

  get 'nota_de_ventas/show'

  get 'multas/index'

  get 'multas/show'

  get '/log_auditorias' => 'log_auditoria#index'
  get 'log_auditorias/index'

  get 'log_auditorias/show'

  get 'ejemplar_estados/index'

  get 'ejemplars/index'

  get 'ejemplars/show'

  get 'disfrazs/index'

  get 'disfrazs/show'

  get 'devolucions/index'

  get 'devolucions/show'

  get 'detalle_devolucions/show'

  get 'detalle_arriendos/show'

  get 'clientes/index'

  get 'clientes/show'

  get 'categorias/index'

  get 'categoria/new' => 'categoria#new'

  post 'categoria/index' => 'categorias#create'

  get 'categoria/index' => 'categorias#index'

  get '/arriendo_estados' => 'arriendo_estados#index'

  get 'arriendo_estado/new' => 'arriendo_estados#new'

  resources :clientes do
    resources :pedidos, :arriendos, :devolucions
    resource :cliente_estado
  end

  resources :categoria

  resources :categorias do
    resources :disfrazs
  end

  resources :cliente_estados

  resources :arriendos do
    resources :detalle_arriendos,:devolucions
    resource :transicion_est_arriendo, :multa,:nota_de_venta
  end

  resources :devolucions
  resources :disfrazs do
    resources :ejemplars
  end

  resources :ejemplars do
    resource :ejemplar_estado
  end

  resources :ejemplar_estados

  resources :log_auditorias

  resources :multas
  resources :nota_de_ventas

  resources :parametro_sistemas

  resources :pedidos do
    resources :pedidos_detalles
  end

  resources :transicion_arriendos
  resources :transicion_est_arriendos
  resources :transicion_est_ejemplars
  resources :transicion_est_pedidos
  resources :transicion_est_vendedors

  resources :vendedors do
    resources :arriendos, :devolucions
    resource :vendedor_estado
  end

  resources :log_auditorias
  resources :vendedor_estados

   root 'home#index'

end

app/controllers/transicion_arriendos_controller.rb
class TransicionArriendosController < ApplicationController
  before_action :set_transicion_arriendo, only: [:show, :edit, :update, :destroy]

  # GET /transicion_arriendos
  # GET /transicion_arriendos.json
  def index
    @transicion_arriendos = TransicionArriendo.all
  end

  # GET /transicion_arriendos/1
  # GET /transicion_arriendos/1.json
  def show
  end

  # GET /transicion_arriendos/new
  def new
    @transicion_arriendo = TransicionArriendo.new
  end

  # GET /transicion_arriendos/1/edit
  def edit
  end

  # POST /transicion_arriendos
  # POST /transicion_arriendos.json
  def create
    @transicion_arriendo = TransicionArriendo.new(transicion_arriendo_params)

    respond_to do |format|
      if @transicion_arriendo.save
        format.html { redirect_to @transicion_arriendo, notice: 'Transicion arriendo was successfully created.' }
        format.json { render :show, status: :created, location: @transicion_arriendo }
      else
        format.html { render :new }
        format.json { render json: @transicion_arriendo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transicion_arriendos/1
  # PATCH/PUT /transicion_arriendos/1.json
  def update
    respond_to do |format|
      if @transicion_arriendo.update(transicion_arriendo_params)
        format.html { redirect_to @transicion_arriendo, notice: 'Transicion arriendo was successfully updated.' }
        format.json { render :show, status: :ok, location: @transicion_arriendo }
      else
        format.html { render :edit }
        format.json { render json: @transicion_arriendo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transicion_arriendos/1
  # DELETE /transicion_arriendos/1.json
  def destroy
    @transicion_arriendo.destroy
    respond_to do |format|
      format.html { redirect_to transicion_arriendos_url, notice: 'Transicion arriendo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transicion_arriendo
      @transicion_arriendo = TransicionArriendo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transicion_arriendo_params
      params[:transicion_arriendo]
    end
end

app/helpers/transicion_arriendos_helper.rb
module TransicionArriendosHelper
end

app/views/transicion_arriendos/_form.html.erb
<%= form_for(@transicion_arriendo) do |f| %>
  <% if @transicion_arriendo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transicion_arriendo.errors.count, "error") %> prohibited this transicion_arriendo from being saved:</h2>

      <ul>
      <% @transicion_arriendo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transicion_arriendos/edit.html.erb
<h1>Editing transicion_arriendo</h1>

<%= render 'form' %>

<%= link_to 'Show', @transicion_arriendo %> |
<%= link_to 'Back', transicion_arriendos_path %>

app/views/transicion_arriendos/index.html.erb
<h1>Listing transicion_arriendos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transicion_arriendos.each do |transicion_arriendo| %>
      <tr>
        <td><%= link_to 'Show', transicion_arriendo %></td>
        <td><%= link_to 'Edit', edit_transicion_arriendo_path(transicion_arriendo) %></td>
        <td><%= link_to 'Destroy', transicion_arriendo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transicion arriendo', new_transicion_arriendo_path %>

app/views/transicion_arriendos/new.html.erb
<h1>New transicion_arriendo</h1>

<%= render 'form' %>

<%= link_to 'Back', transicion_arriendos_path %>

app/views/transicion_arriendos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_transicion_arriendo_path(@transicion_arriendo) %> |
<%= link_to 'Back', transicion_arriendos_path %>